default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: biblioteca_api_development

test:
  <<: *default
  database: biblioteca_api_test

production:
  <<: *default
  database: biblioteca_api_production
  username: biblioteca_api
  password: <%= ENV['BIBLIOTECA_API_DATABASE_PASSWORD'] %>
